apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hotel-Room-Booking-and-Management-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Hotel-Room-Booking-and-Management-backend
  template:
    metadata:
      labels:
        app: Hotel-Room-Booking-and-Management-backend
    spec:
      containers:
        - name: backend
          image: docker.io/shandeep04/hotel-room-booking-and-management-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: MONGO_URI
              value: "mongodb+srv://shandeep4621:shandeep4621@cluster0.dpijowj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
          imagePullPolicy: Always

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: Hotel-Room-Booking-and-Management-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: Hotel-Room-Booking-and-Management-frontend
  template:
    metadata:
      labels:
        app: Hotel-Room-Booking-and-Management-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/shandeep04/hotel-room-booking-and-management-frontend:latest
          ports:
            - containerPort: 3000
          imagePullPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: Hotel-Room-Booking-and-Management-backend
  ports:
    - port: 5000
      targetPort: 5000
  type: ClusterIP

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: Hotel-Room-Booking-and-Management-frontend
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30001
